-- Public SEO blog. Posts are generated by the daily cron (service role) and
-- read publicly when status = 'published'. Body is a list of typed blocks
-- (heading/paragraph/list/quote/cta) so rendering stays consistent and safe.
create table if not exists public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  excerpt text not null default '',
  tags text[] not null default '{}',
  cover_gradient text not null default 'from-indigo-500 to-purple-600',
  body jsonb not null default '[]'::jsonb,
  read_minutes int not null default 4,
  status text not null default 'published',
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.blog_posts enable row level security;

drop policy if exists "public read published blog posts" on public.blog_posts;
create policy "public read published blog posts"
  on public.blog_posts for select
  using (status = 'published');

-- No insert/update/delete policy: only the service role (cron) writes.
create index if not exists blog_posts_published_idx on public.blog_posts (published_at desc) where status = 'published';
